# Generated by Django 4.2.4 on 2024-08-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyproduct',
            old_name='compnay',
            new_name='company',
        ),
    ]
