# Generated by Django 4.2.4 on 2024-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproduct',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
