# Generated by Django 4.2.4 on 2024-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyproduct_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproduct',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
