# Generated by Django 4.2.4 on 2024-07-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_description_category_image_and_more'),
        ('cart', '0002_rename_name_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
