# Generated by Django 4.2.4 on 2024-07-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash on delivery', 'Cash on delivery')], default='Credit Card', max_length=20),
        ),
    ]
