# Generated by Django 4.2.4 on 2024-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_discount_order_discount_amount_order_discount_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
